# Generated by Django 2.1 on 2020-05-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseinfo',
            name='p_sex',
        ),
    ]
