# Generated by Django 2.1 on 2020-05-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_remove_houseinfo_p_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='selling_house_number',
            field=models.IntegerField(default=0),
        ),
    ]
