# Generated by Django 2.1 on 2020-05-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_houseinfo_selling_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='house_avg_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='increase_house',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='increase_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='people_seehouse_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='trade_number_last90day',
            field=models.IntegerField(default=0),
        ),
    ]
