# Generated by Django 2.1 on 2020-05-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20200502_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseinfo',
            name='p_age',
        ),
        migrations.RemoveField(
            model_name='houseinfo',
            name='p_name',
        ),
    ]
