# Generated by Django 2.1 on 2020-05-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20200502_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
