# Generated by Django 2.1 on 2020-05-06 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20200506_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 6, 13, 17, 23, 791943, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
